API_KEY = 'ufSA5pgQvHc1nYztosoaLgF3rLUYBOKufYj4MlwkZtx7JSXnLPhQe5Bnmw7NgXiH'
API_SECRET = 'QKPYkq46BtCYZdwFdrJpz7parIskNPxBpkNFXzjGwhbEAei0EUtp50RREyAgrCLc'
RSI_PERIOD = 14
RSI_OVERBOUGHT = 70
RSI_OVERSOLD = 30
TRADE_SYMBOL = "ETHUSD"
TRADE_QUANTITY = 0.012